"""Every generated-view gate CI runs, as data (ADR 0015 review, card 2).

THIS LIST REPLACES a 1,009-line workflow, a hand-maintained cost manifest, a bin-packing
script and a local runner that re-derived the list from the YAML. One gate is one entry:
the exact argv CI ran before this file existed, the tier it runs in, whether it may run
beside other gates, and the per-gate timeout the workflow step carried (in seconds, verbatim
from `timeout-minutes`). `tests/test_gates.py` runs them; `pytest -n auto` is the local
mirror `src/check_all.py` used to be.

SERIAL MEANS SERIAL. A `--selftest` gate breaks a fixture in the working tree, watches a
rule fire, and restores it, so it must never run beside ANY other gate — not another
selftest, not a `--check` reading the fixture mid-mutation. `serial=True` puts a gate in
the second phase, which runs one at a time after the parallel phase has drained, with a
dirty-tree guard between gates (`tests/conftest.py`). Every gate that is not a plain
`--check` is serial; the two that are neither (`--drift`, a bare invocation) cost 5 s
together and are not worth a judgement about their side effects.

ADDING A GATE is adding an entry. There is no second place to register it.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class Gate:
    name: str
    argv: tuple  # run from the repository root, exactly as CI ran it
    tier: str    # "pr" runs on every PR and push; "nightly" on schedule/dispatch only
    serial: bool # see the module docstring
    timeout: int # seconds; the workflow step's own timeout-minutes, verbatim


GATES = (
    Gate('Constitution ingest skip rules must all be able to fail',
         ('python3', 'src/ingest_constitution.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('The Constitution catalog must match what is on disk',
         ('python3', 'src/ingest_constitution.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('The Constitution drift report must be silent on the committed snapshot',
         ('python3', 'src/ingest_constitution.py', '--drift', '_meta/snapshots/oregon-constitution.txt'),
         tier='pr', serial=True, timeout=120),
    Gate('Bulletin reader rules must all be able to fail',
         ('python3', 'src/check_bulletin.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('The monthly Bulletin report must file one issue, or none',
         ('python3', 'src/bulletin_report.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('External-citation catalog must be current',
         ('python3', 'src/scan_external_citations.py', '--check'),
         tier='pr', serial=False, timeout=480),
    Gate('Semantic topic map must be current (reads committed UMAP cache)',
         ('python3', 'src/build_topic_map.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Governor-priorities dataset must match the graph',
         ('python3', 'src/build_governor_priorities_data.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Conflict-candidates dataset must match the graph (verifies every citation)',
         ('python3', 'src/build_conflict_candidates_data.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('ADR 0006 must say what the OAR hash watch actually covers',
         ('python3', 'src/oar_watch_coverage.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('...and that rule must be able to fail (Bulletin-named rules watched)',
         ('python3', 'src/seed_oar_watch.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Enabling authorities must match the reviewed table',
         ('python3', 'src/link_enabling_authority.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Bulletin worklist must hold up against the corpus',
         ('python3', 'src/check_bulletin.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Ingest-status vocabulary must be declared once',
         ('python3', 'src/ingest_status.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Legal status must be written once and read everywhere else',
         ('python3', 'src/legal_status.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Ingest scripts must not write a verification stamp nobody earned',
         ('python3', 'src/verification_stamp.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('A stated figure must be gated against the census that produces it',
         ('python3', 'src/stated_census.py', '--check', 'CONTEXT.md', 'src/record_name_basis.py'),
         tier='pr', serial=False, timeout=120),
    Gate('...and that rule must be able to fail (stated-figure census)',
         ('python3', 'src/stated_census.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Check-rule ledger must be able to fail (selftest)',
         ('python3', 'src/check_rule_ledger.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Conflict-coverage ledger must be current',
         ('python3', 'src/build_conflict_coverage.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Triage write path must lose nothing',
         ('python3', 'src/triage_conflicts.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Amendments must re-ingest without reaching a rule out of force',
         ('python3', 'src/reingest_oar.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('ORS disposition catalog must be current',
         ('python3', 'src/build_ors_disposition.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('llms.txt must be current, and name every chapter we mirror',
         ('python3', 'src/build_llms.py', '--check', '--selftest'),
         tier='pr', serial=False, timeout=480),
    Gate('Policy-documentation-gap view must be current',
         ('python3', 'src/build_policy_gap.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Regulatory-freshness dataset must match the graph',
         ('python3', 'src/build_freshness_data.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Regulatory-freshness visualization must be current',
         ('python3', 'src/build_freshness.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate("A document's two spellings of its source hash must agree",
         ('python3', 'src/provenance_spelling.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('A document mirroring an OARD results list must be recorded as one',
         ('python3', 'src/results_page_documents.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Every rule the Bulletin named and this corpus holds must be watched',
         ('python3', 'src/seed_oar_watch.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Agency registry must keep its contract',
         ('python3', 'src/catalog_agencies.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('The OAR catalog must agree with the registry, the disk, and its own rules',
         ('python3', 'src/catalog_agreement.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Recheck cadences must be declared once, and every group must validate',
         ('python3', 'src/check_updates.py', '--check'),
         tier='pr', serial=False, timeout=300),
    Gate("The Bulletin report must carry what it counts, on the Bulletin's cadence",
         ('python3', 'src/bulletin_report.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('ORS ingest title-anchoring check must refuse a one-shared-word mis-anchor',
         ('python3', 'src/ingest_ors.py', '--selftest'),
         tier='pr', serial=True, timeout=600),
    Gate('ORS catalog TOC xref-range parsing must be able to fail (selftest)',
         ('python3', 'src/catalog_ors.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Citation schemes must resolve, and refuse, what they claim',
         ('python3', 'src/citation_schemes.py', '--selftest'),
         tier='pr', serial=True, timeout=480),
    Gate('Agency-registry contract rules must all be able to fail',
         ('python3', 'src/catalog_agencies.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Conflict evaluation must measure against pinned ground truth',
         ('python3', 'src/eval_conflicts.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('A suspended rule keeps its authority edges, a repealed one does not',
         ('python3', 'src/link_graph.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Statute-operationalization view must be current',
         ('python3', 'src/build_statute_fan.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Policy-age visualization must be current',
         ('python3', 'src/build_policy_age.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate("A snapshot's two spellings must agree",
         ('python3', 'src/snapshot_identity.py', '--check'),
         tier='pr', serial=False, timeout=180),
    Gate('Every registry-name read must be classified',
         ('python3', 'src/name_readers.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Relation kinds must match the derivation',
         ('python3', 'src/derive_relation_kinds.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Every amendment the Bulletin filed must be recorded as re-ingested',
         ('python3', 'src/reingest_oar.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('ORS chapter-gap catalog must be current',
         ('python3', 'src/scan_ors_citations.py', '--check'),
         tier='pr', serial=False, timeout=600),
    Gate('Executive-order signed-date parser',
         ('python3', 'src/ingest_eo.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Conflict-catalog merge must not drop prior candidates',
         ('python3', 'src/analyze_conflicts.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Enabling-authority rules must all be able to fail',
         ('python3', 'src/link_enabling_authority.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Relation-kind derivation rules must all be able to fail',
         ('python3', 'src/derive_relation_kinds.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Cadence rules must all be able to fail',
         ('python3', 'src/check_updates.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Ingest-status vocabulary rule must be able to fail',
         ('python3', 'src/ingest_status.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Verification-stamp rule must be able to fail',
         ('python3', 'src/verification_stamp.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Shared corpus-walk and division-status rules must both be able to fail',
         ('python3', 'src/repo_lib.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Legal status must have exactly one writer',
         ('python3', 'src/legal_status.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Relationship graph must be current',
         ('python3', 'src/link_graph.py', '--check'),
         tier='pr', serial=False, timeout=420),
    Gate('OAR upstream_tracking field must match the source manifest',
         ('python3', 'src/mark_upstream_tracking.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Agency authority-graph visualization must be current',
         ('python3', 'src/build_agency_graph.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Authority-chain explorer must be current',
         ('python3', 'src/build_authority_explorer.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Semantic vector index must be current (soft-pass if not built)',
         ('python3', 'src/build_embeddings.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Budget agency codes must match the reviewed mapping',
         ('python3', 'src/link_budget_codes.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('Snapshot-identity gate must be able to fail (selftest)',
         ('python3', 'src/snapshot_identity.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('...and that rule must be able to fail (source-hash spellings)',
         ('python3', 'src/provenance_spelling.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('...and that rule must be able to fail (OARD results-list documents)',
         ('python3', 'src/results_page_documents.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('...and that rule must be able to fail (OAR hash-watch coverage)',
         ('python3', 'src/oar_watch_coverage.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Registry-name classification gate must fire (selftest)',
         ('python3', 'src/name_readers.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('OAR enrichment stamps the OAR name (selftest)',
         ('python3', 'src/enrich_oar.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('OAR discovery is keyed on the OAR name (selftest)',
         ('python3', 'src/catalog_oar.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('OAR catalog row matches its declared shape',
         ('python3', 'src/catalog_oar.py', '--check'),
         tier='pr', serial=False, timeout=120),
    Gate('...and those rules must be able to fail (catalog agreement)',
         ('python3', 'src/catalog_agreement.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('OAR catalog membership has exactly one writer (selftest)',
         ('python3', 'src/ingest_oar.py', '--selftest'),
         tier='pr', serial=True, timeout=120),
    Gate('Mechanical conflict findings must be current',
         ('python3', 'src/detect_mechanical.py', '--check'),
         tier='pr', serial=False, timeout=300),
    Gate('ORS chapter-gap classification must all be able to fail',
         ('python3', 'src/scan_ors_citations.py', '--selftest'),
         tier='pr', serial=True, timeout=600),
    Gate('STATUS.md must be current',
         ('corpus-generate-status', '--config', '_meta/corpus.yml', '--output', 'STATUS.md', '--check'),
         tier='pr', serial=False, timeout=360),
    Gate('Agency overview must be current',
         ('python3', 'src/build_agency_index.py', '--check'),
         tier='pr', serial=False, timeout=420),
    Gate('Agency profile engine selftest (nightly)',
         ('python3', 'src/agency_profile.py', '--selftest'),
         tier='nightly', serial=True, timeout=900),
    Gate('MCP query engine smoke test (nightly)',
         # A whole program, verbatim from the step that ran it: flattening its newlines
         # turned it into an IndentationError on the first local run of this suite.
         ('python3', '-c', "\nimport sys\nfrom corpus_toolkit import config as config_mod\nfrom corpus_toolkit.mcp.framework import CorpusFramework\nconfig = config_mod.load('_meta/corpus.yml')\nfw = CorpusFramework(config)\nfails = []\ndef check(name, cond):\n    print(('PASS ' if cond else 'FAIL ') + name)\n    if not cond: fails.append(name)\nr = fw.resolve_citation('OAR 125-800-0020')\ncheck('renumbered OAR citation resolves', any(m['id']=='oar-128-030-0020' for m in r['matches']))\nr = fw.resolve_citation('ORS 276A.300')\ncheck('ORS citation resolves', any(m['id']=='ors-276a.300' for m in r['matches']))\nr = fw.resolve_citation('Or. Const. Art. VI, sec. 1')\ncheck('constitutional citation resolves', any(m['id']=='orconst-art-vi-sec-1' for m in r['matches']))\nr = fw.resolve_citation('Or. Const. Art. VI, sec. 99')\ncheck('a section the page does not print resolves to nothing', r.get('unresolved') and not r['matches'])\ncheck('...and says the page prints no such section', 'no section 99' in (r.get('note') or ''))\nr = fw.get_document('oar-128-030-0020')\ncheck('get_document returns body + disclaimer', 'body' in r and r.get('disclaimer'))\nr = fw.corpus_overview()\ncheck('corpus_overview counts documents', sum(r['documents_by_type'].values()) > 60000)\nr = fw.issuing_body_profile('department-of-administrative-services')\ncheck('issuing_body_profile has real doc counts', isinstance(r.get('in_repo'), dict) and sum(r['in_repo'].values()) > 100)\nsys.exit(1 if fails else 0)\n"),
         tier='nightly', serial=True, timeout=600),
    Gate('Policy-age dataset must match the corpus (nightly; full-corpus scan)',
         ('python3', 'src/build_policy_age_data.py', '--check'),
         tier='nightly', serial=False, timeout=600),
    Gate('Review queue must be current (nightly)',
         ('python3', 'src/review_queue.py', '--check'),
         tier='nightly', serial=False, timeout=600),
    Gate("ORS frontmatter must match each statute's own history notes (nightly)",
         ('python3', 'src/enrich_statutes.py', '--check'),
         tier='nightly', serial=False, timeout=600),
    Gate("OAR frontmatter must match each rule's own structured lines (nightly)",
         ('python3', 'src/enrich_oar.py', '--check'),
         tier='nightly', serial=False, timeout=900),
)


def by_tier(tier: str):
    return [g for g in GATES if g.tier == tier]
